interactivecalendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('calendar/', views.calendar_index, name='calendar_index'),
    path('activities/', views.activities_index, name='activities_index'),
    path('activities/<int:activity_id>/', views.activities_detail, name='activities_detail'),
    path('activities/create/', views.ActivityCreate.as_view(), name='activities_create'),
    path('activities/<int:pk>/update/', views.ActivityUpdate.as_view(), name='activities_update'),
    path('activities/<int:pk>/delete/', views.ActivityDelete.as_view(), name='activities_delete'),
    path('activities/<int:activity_id>/add_nutrition/', views.add_nutrition, name='add_nutrition'),
    path('sleep/', views.sleep_index, name='sleep_index'),
    path('sleep/<int:sleep_id>/', views.sleep_detail, name='sleep_detail'),
    path('sleep/create/', views.SleepCreate.as_view(), name='sleep_create'),
    path('sleep/<int:pk>/update/', views.SleepUpdate.as_view(), name='sleep_update'),
    path('sleep/<int:pk>/delete/', views.SleepDelete.as_view(), name='sleep_delete'),
    path('dashboard', views.dashboard_index, name='dashboard_index'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Activity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    date = models.DateField('Date (yyyy-mm-dd)')
    type = models.CharField(max_length=25)
    time = models.DurationField('Activity Duration (hh:mm:ss)')
    distance = models.IntegerField('Distance (m)')
    elevationgain = models.IntegerField('Elevation Gain (m)')
    calories = models.IntegerField('Calories Burned')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('activities_detail', kwargs={'activity_id': self.id})

    class Meta:
        ordering = ['-date']

    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Nutrition(models.Model):
    name = models.CharField(max_length=75, default='N/A')
    fat = models.IntegerField('Fat (g)')
    protein = models.IntegerField('Protein (g)')
    carbohydrates = models.IntegerField('Carbohydrates (g)')
    totalcalories = models.IntegerField('Total Calories Consumed')

    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

class Sleep(models.Model):
    date = models.DateField('Date (yyyy-mm-dd)')
    bedtime = models.TimeField()
    awake = models.TimeField()
    mood = models.CharField(max_length=25)
    note = models.TextField(max_length=150)

    def get_absolute_url(self):
        return reverse('sleep_detail', kwargs={'sleep_id': self.id})

    class Meta:
        ordering = ['-date']

    user = models.ForeignKey(User, on_delete=models.CASCADE)

main_app/forms.py
from django.forms import ModelForm
from .models import Nutrition

class NutritionForm(ModelForm):
    class Meta:
        model = Nutrition
        fields = '__all__'
        exclude = ['activity', 'user']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Import FORMS
from .forms import NutritionForm

# Import MODELS
from .models import Activity, Sleep
from datetime import datetime


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('calendar_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def calendar_index(request):
  return render(request, 'calendar/index.html')

### This code needs to be fixed to render my sleep and activity data for my modal
@login_required
def fetch_data(request):
    if request.method == 'GET':
        selected_date_str = request.GET.get('selected_date')
        selected_date = datetime.strptime(selected_date_str, '%Y-%m-%d').date()
        
        activities = Activity.objects.filter(date=selected_date, user=request.user)
        sleeps = Sleep.objects.filter(date=selected_date, user=request.user)
        
        return render(request, 'calendar/index.html', {
            'activities': activities,
            'sleeps': sleeps,
        })


@login_required
def activities_index(request):
  activities = Activity.objects.filter(user=request.user)
  return render(request, 'activities/index.html', {
    'activities': activities
  })

@login_required
def activities_detail(request, activity_id):
   activity = Activity.objects.get(id=activity_id)
   nutrition_form = NutritionForm()
   return render(request, 'activities/detail.html', {
      'activity': activity,
      'nutrition_form': nutrition_form,
   })

class ActivityCreate(LoginRequiredMixin, CreateView):
    model = Activity
    fields = ['name', 'description', 'date', 'type', 'time', 'distance', 'elevationgain', 'calories']
    exclude = ['user']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ActivityUpdate(LoginRequiredMixin, UpdateView):
  model = Activity
  fields = ['name', 'description', 'date', 'type', 'time', 'distance', 'elevationgain', 'calories']

class ActivityDelete(LoginRequiredMixin, DeleteView):
  model = Activity
  success_url = '/activities'

@login_required
def add_nutrition(request, activity_id):
  form = NutritionForm(request.POST)
  if form.is_valid():
    new_nutrition = form.save(commit=False)
    new_nutrition.activity_id = activity_id
    new_nutrition.save()
  return redirect('activities_detail', activity_id=activity_id)

@login_required
def sleep_index(request):
  sleeps = Sleep.objects.filter(user=request.user)
  return render(request, 'sleep/index.html', {
    'sleeps': sleeps
  })

@login_required
def sleep_detail(request, sleep_id):
   sleep = Sleep.objects.get(id=sleep_id)
   return render(request, 'sleep/detail.html', {
      'sleep': sleep
   })

class SleepCreate(LoginRequiredMixin, CreateView):
    model = Sleep
    fields = ['date', 'bedtime', 'awake', 'mood', 'note']
    exclude = ['user']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class SleepUpdate(LoginRequiredMixin, UpdateView):
  model = Sleep
  fields = ['date', 'bedtime', 'awake', 'mood', 'note']

class SleepDelete(LoginRequiredMixin, DeleteView):
  model = Sleep
  success_url = '/sleep'

@login_required
def dashboard_index(request):
  return render(request, 'dashboard/index.html')

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Interactive Calendar</h1>
<hr>
<p>Use this calendar at your leisure.</p>
<footer>All Rights Reserved, &copy; 2024 Interactive Calendar</footer>

{% endblock %}

main_app/templates/activities/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Activity Details</h1>


<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><b>{{ activity.name }}</b></span>
        <p><b>Description: </b>{{ activity.description|linebreaks }}</p>
        <p><b>Date: </b>{{ activity.date }}</p>
        {% if activity.type == 'Run' %}
            <p><b>Duration: </b>{{ activity.time }}</p>
            <p><b>Distance: </b>{{ activity.distance }}m</p>
            <p><b>Total Elevation Gain: </b>{{ activity.elevationgain }}</p>
            <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
        {% elif activity.type == 'Ride' %}
            <p><b>Duration: </b>{{ activity.time }}</p>
            <p><b>Distance: </b>{{ activity.distance }}m</p>
            <p><b>Total Elevation Gain: </b>{{ activity.elevationgain }}m</p>
            <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
        {% elif activity.type == 'Swim' %}
            <p><b>Duration: </b>{{ activity.time }}</p>
            <p><b>Distance: </b>{{ activity.distance }}m</p>
            <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
        {% elif activity.type == 'Walk' %}
            <p><b>Duration: </b>{{ activity.time }}</p>
            <p><b>Distance: </b>{{ activity.distance }}m</p>
            <p><b>Total Elevation Gain: </b>{{ activity.elevationgain }}</p>
            <p>Calories burned: {{ activity.calories }}cal</p>
        {% elif activity.type == 'Gym' %}
            <p><b>Duration: </b>{{ activity.time }}</p>
            <p><b>Calories: </b>{{ activity.calories }}cal</p>
        {% elif activity.type == 'Yoga' %}
            <p><b>Duration: </b>{{ activity.time }}</p>
            <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
        {% elif activity.type == 'Other' %}
            <p><b>Duration: </b>{{ activity.time }}</p>
            <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
        {% endif %}
        <div class="card-action">
          <a href="{% url 'activities_update' activity.id %}">Edit</a>
          <a href="{% url 'activities_delete' activity.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>
  <div class="col s6">
    <table class="striped">
      <thead>
        <h4 style="text-align: center; text-decoration: underline;">Nutrition</h4>
        <tr><th>Name</th><th>Fat (g)</th><th>Protein (g)</th><th>Carbohydrates (g)</th><th>Total Calories</th></tr>
      </thead>
      <tbody>
        {% for nutrition in activity.nutrition_set.all %}
          <tr>
            <td>{{nutrition.name}}</td>
            <td>{{nutrition.fat}}</td>
            <td>{{nutrition.protein}}</td>
            <td>{{nutrition.carbohydrates}}</td>
            <td><b>{{nutrition.totalcalories}}</b></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <form action="{% url 'add_nutrition' activity.id %}" method="POST">
      {% csrf_token %}
      {{ nutrition_form.as_p }}
      <input type="submit" class="btn" value="Add Nutrition">
    </form>
  </div>
</div>

{% endblock %}

main_app/templates/activities/index.html
{% extends 'base.html' %}
{% block content %}

<h1>My Activities</h1>

{% for activity in activities %}
<div class="card">
    <a href="{% url 'activities_detail' activity.id %}">
        <div class="card-content">
            <span class="card-title"><b>{{ activity.name }}</b></span>
            <p><b>Description: </b>{{ activity.description|linebreaks }}</p>
            <p><b>Date: </b>{{ activity.date }}</p>
            {% if activity.type == 'Run' %}
                <p><b>Duration: </b>{{ activity.time }}</p>
                <p><b>Distance: </b>{{ activity.distance }}m</p>
                <p><b>Total Elevation Gain: </b>{{ activity.elevationgain }}</p>
                <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
            {% elif activity.type == 'Ride' %}
                <p><b>Duration: </b>{{ activity.time }}</p>
                <p><b>Distance: </b>{{ activity.distance }}m</p>
                <p><b>Total Elevation Gain: </b>{{ activity.elevationgain }}m</p>
                <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
            {% elif activity.type == 'Swim' %}
                <p><b>Duration: </b>{{ activity.time }}</p>
                <p><b>Distance: </b>{{ activity.distance }}m</p>
                <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
            {% elif activity.type == 'Walk' %}
                <p><b>Duration: </b>{{ activity.time }}</p>
                <p><b>Distance: </b>{{ activity.distance }}m</p>
                <p><b>Total Elevation Gain: </b>{{ activity.elevationgain }}</p>
                <p>Calories burned: {{ activity.calories }}cal</p>
            {% elif activity.type == 'Gym' %}
                <p><b>Duration: </b>{{ activity.time }}</p>
                <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
            {% elif activity.type == 'Yoga' %}
                <p><b>Duration: </b>{{ activity.time }}</p>
                <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
            {% elif activity.type == 'Other' %}
                <p><b>Duration: </b>{{ activity.time }}</p>
                <p><b>Calories burned: </b>{{ activity.calories }}cal</p>
            {% endif %}
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Interactive Calendar</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Interactive Calendar</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'calendar_index' %}">Calendar</a></li>
            <li><a href="{% url 'activities_index' %}">My Activities</a></li>
            <li><a href="{% url 'activities_create' %}">Add Manual Activity</a></li>
            <li><a href="{% url 'sleep_index' %}">My Sleep</a></li>
            <li><a href="{% url 'sleep_create' %}">Add Sleep</a></li>
            <li><a href="{% url 'dashboard_index' %}">My Dashboard</a></li>
            <li><form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit">Log Out</button>
          </form></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2024 Interactive Calendar &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/calendar/index.html
{% extends 'base.html' %} {% block content %} {% block extra_css %}
<style>
  #month-year {
    font-size: 4vw; 
    margin-bottom: 2vh; 
    text-align: center;
  }

  .calendar {
    margin-top: 2vh; 
  }

  .days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    text-align: center;
  }

  .day {
    text-align: center;
    padding: 1vh; 
    border: 1px solid #ddd;
  }

  .day-title {
    text-align: center;
    padding: 1vh; 
    font-weight: bold;
    font-size: 2vw; 
  }

  .day-titles {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    text-align: center;
    margin-bottom: 1vh; 
  }

  .day-title-item {
    font-weight: bold;
    font-size: 1.5vw; 
  }

  .day:hover {
    background-color: #b1e5ff;
    cursor: pointer;
  }

  .current-day {
    background-color: #039be5; 
    color: white; 
    font-weight: bold;
  }

  .nav-buttons {
    display: flex;
    justify-content: space-between;
    margin-bottom: 2vh; 
  }

  .nav-button {
    padding: 1vh 2vw; 
    border-radius: 5px;
    background-color: #039be5;
    color: white;
    cursor: pointer;
    font-size: 2vw; 
  }
</style>
{% endblock %}

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Calendar</title>
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
  />
  <link
    href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet"
  />
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col s12">
        <div class="card">
          <div class="card-content">
            <span class="card-title" id="month-year"></span>

            <div class="row nav-buttons">
              <div class="col s6">
                <button
                  class="btn waves-effect waves-light nav-button"
                  id="prev-month"
                >
                  <i class="material-icons">arrow_back</i>
                </button>
              </div>
              <div class="col s6">
                <button
                  class="btn waves-effect waves-light nav-button right"
                  id="next-month"
                >
                  <i class="material-icons">arrow_forward</i>
                </button>
              </div>
            </div>

            <div class="day-titles">
              <div class="day-title-item">Sun</div>
              <div class="day-title-item">Mon</div>
              <div class="day-title-item">Tue</div>
              <div class="day-title-item">Wed</div>
              <div class="day-title-item">Thu</div>
              <div class="day-title-item">Fri</div>
              <div class="day-title-item">Sat</div>
            </div>

            <div class="calendar">
              <div class="row">
                <div class="col s12">
                  <div class="days">
                    <!-- Days will be dynamically generated here -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- Add Data Modal -->
<div id="addDataModal" class="modal">
  <div class="modal-content">
      {% for activity in activities %}
          <p>{{ activity.name }}</p>

      {% empty %}
          <p>No activities for selected date</p>
      {% endfor %}

      {% for sleep in sleeps %}
          <p>Bedtime: {{ sleep.bedtime }}</p>
          <p>Awake: {{ sleep.awake }}</p>

      {% empty %}
          <p>No sleep data for selected date</p>
      {% endfor %}

      <h4>Add Sleep or Activity Data</h4>
      <p>What would you like to add?</p>
      <div class="row">
          <div class="col s6">
              <button class="btn waves-effect waves-light" id="addSleepBtn">
                  Add Sleep
              </button>
          </div>
          <div class="col s6">
              <button class="btn waves-effect waves-light" id="addActivityBtn">
                  Add Activity
              </button>
          </div>
      </div>
  </div>
</div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const prevMonthBtn = document.getElementById("prev-month");
      const nextMonthBtn = document.getElementById("next-month");
      const monthYearText = document.getElementById("month-year");
      const daysContainer = document.querySelector(".days");
  
      // Get current date
      const today = new Date();
      let currentMonth = today.getMonth();
      let currentYear = today.getFullYear();
  
      // Initialize the modal and its event listeners
      let dataModal;
  
      function initializeModal() {
        // Get modal instance
        const addDataModal = document.getElementById("addDataModal");
        dataModal = M.Modal.init(addDataModal);
  
        const dayElements = document.querySelectorAll(".day");
        dayElements.forEach((day) => {
          day.addEventListener("click", function () {
            dataModal.open();
          });
        });
  
        const addSleepBtn = document.getElementById("addSleepBtn");
        addSleepBtn.addEventListener("click", function () {
          dataModal.close();
          window.location.href = "/sleep/create";
        });
  
        const addActivityBtn = document.getElementById("addActivityBtn");
        addActivityBtn.addEventListener("click", function () {
          dataModal.close();
          window.location.href = "/activities/create";
        });
      }
  
      function renderCalendar(month, year) {
        // Clear previous calendar
        daysContainer.innerHTML = "";
  
        monthYearText.textContent = `${getMonthName(month)} ${year}`;
  
        const firstDayOfMonth = new Date(year, month, 1);
        const startDayOfWeek = firstDayOfMonth.getDay(); // 0 for Sunday, 1 for Monday
  
        const numDaysInMonth = new Date(year, month + 1, 0).getDate();
  
        for (let i = 0; i < startDayOfWeek; i++) {
          const prevMonthDay = numDaysInMonth - startDayOfWeek + i + 1;
          const dayElement = createDayElement(prevMonthDay, "other-month");
          daysContainer.appendChild(dayElement);
        }
  
        for (let day = 1; day <= numDaysInMonth; day++) {
          const className =
            day === today.getDate() &&
            month === today.getMonth() &&
            year === today.getFullYear()
              ? "current-day"
              : "current-month"; 
          const dayElement = createDayElement(day, className);
          daysContainer.appendChild(dayElement);
        }
  
        initializeModal();
      }
  
      function createDayElement(day, className) {
        const dayElement = document.createElement("div");
        dayElement.textContent = day;
        dayElement.className = `day ${className}`;
        return dayElement;
      }
  
      function getMonthName(month) {
        const monthNames = [
          "January",
          "February",
          "March",
          "April",
          "May",
          "June",
          "July",
          "August",
          "September",
          "October",
          "November",
          "December",
        ];
        return monthNames[month];
      }
  
      renderCalendar(currentMonth, currentYear);
  
      prevMonthBtn.addEventListener("click", function () {
        currentMonth--;
        if (currentMonth < 0) {
          currentMonth = 11;
          currentYear--;
        }
        renderCalendar(currentMonth, currentYear);
      });
  
      nextMonthBtn.addEventListener("click", function () {
        currentMonth++;
        if (currentMonth > 11) {
          currentMonth = 0;
          currentYear++;
        }
        renderCalendar(currentMonth, currentYear);
      });
    });
  </script>
</body>
{% endblock %}

main_app/templates/dashboard/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dashboard</h1>
<p>This page will provide graphical representations of the user's sleep, activity, and nutrition data.</p>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>
<p>This homepage is still under construction at the moment.</p>
{% endblock %}

main_app/templates/main_app/activity_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Activity</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn">
    <a href="{% url 'activities_detail' activity.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/activity_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
  <h1>Edit Activity</h1>
{% else %}
  <h1>Add Manual Activity</h1>
{% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>

{% endblock %}

main_app/templates/main_app/sleep_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Sleep Data</h1>

  <h4>Are you sure you want to delete your sleep data from {{ sleep.date }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn">
    <a href="{% url 'sleep_detail' sleep.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/sleep_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
  <h1>Edit Sleep Data</h1>
{% else %}
  <h1>Add Sleep Data</h1>
{% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/sleep/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>My Sleep</h1>
<div class="card">
      <div class="card-content">
        <span class="card-title">{{ sleep.date }}</span>
        <p><b>Bed-Time: </b>{{ sleep.bedtime }}</p>
        <p><b>Awake-Time: </b>{{ sleep.awake }}</p>
        <p><b>Wake-Up Mood: </b>{{ sleep.mood }}</p>
        <p><b>Notes: </b>{{ sleep.note|linebreaks }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'sleep_update' sleep.id %}">Edit</a>
        <a href="{% url 'sleep_delete' sleep.id %}">Delete</a>
      </div>
  </div>

{% endblock %}

main_app/templates/sleep/index.html
{% extends 'base.html' %}
{% block content %}

<h1>My Sleep Log</h1>

{% for sleep in sleeps %}
<div class="card">
    <a href="{% url 'sleep_detail' sleep.id %}">
      <div class="card-content">
        <span class="card-title">{{ sleep.date }}</span>
        <p><b>Bed-Time: </b>{{ sleep.bedtime }}</p>
        <p><b>Awake-Time: </b>{{ sleep.awake }}</p>
        <p><b>Wake-Up Mood: </b>{{ sleep.mood }}</p>
        <p><b>Notes: </b>{{ sleep.note|linebreaks }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
  
{% endblock %}